# Generated by Django 4.1.7 on 2023-03-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("isin", models.CharField(max_length=255)),
                ("assetName", models.CharField(max_length=255)),
                ("icon", models.ImageField(upload_to="icons/")),
                ("currency", models.CharField(max_length=255)),
                ("settlementCurrency", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("assetType", models.CharField(max_length=255)),
                ("isTradeble", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
