# Generated by Django 4.1.7 on 2023-03-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_assetname_asset_issuer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Asset",
            new_name="portfolio",
        ),
    ]
