# Generated by Django 4.1.7 on 2023-03-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_rename_settlementcurrency_assets_settlement_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assets",
            old_name="assetType",
            new_name="asset_type",
        ),
        migrations.RenameField(
            model_name="assets",
            old_name="isTradable",
            new_name="is_tradable",
        ),
    ]
