# Generated by Django 4.1.7 on 2023-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_remove_transaction_name_alter_transaction_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_currency",
            field=models.CharField(max_length=255),
        ),
    ]
