# Generated by Django 4.1.7 on 2023-04-13 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_alter_transaction_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="time_transaction",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 13, 19, 16, 27, 278783)
            ),
        ),
    ]
