# Generated by Django 4.1.7 on 2023-04-14 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_transaction_time_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["time_transaction"]},
        ),
        migrations.AlterField(
            model_name="asset",
            name="icon",
            field=models.ImageField(null=True, upload_to="icons/"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="time_transaction",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 14, 17, 50, 49, 59930)
            ),
        ),
    ]
