# Generated by Django 4.1.7 on 2023-04-20 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_alter_transaction_options_alter_asset_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="description",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="time_transaction",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 20, 18, 47, 57, 948953)
            ),
        ),
    ]
