# Generated by Django 4.1.7 on 2023-04-20 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_remove_asset_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="time_transaction",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 20, 19, 54, 35, 124679)
            ),
        ),
    ]
