# Generated by Django 4.1.7 on 2023-04-21 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_alter_asset_asset_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="isin",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="time_transaction",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 21, 18, 44, 11, 382577)
            ),
        ),
    ]
