# Generated by Django 4.1.7 on 2023-04-24 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_alter_asset_isin_alter_transaction_time_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="broker",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="time_transaction",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 24, 11, 8, 8, 328476)
            ),
        ),
    ]
