# Generated by Django 4.1.7 on 2023-04-24 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_remove_transaction_broker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="time_transaction",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 24, 19, 22, 54, 565700)
            ),
        ),
    ]
