# Generated by Django 4.1.7 on 2023-04-24 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_alter_transaction_time_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="payment_currency",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="time_transaction",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 24, 19, 34, 39, 700880)
            ),
        ),
    ]
