# Generated by Django 4.1.7 on 2023-04-24 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_remove_asset_payment_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="fee",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="tax",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="time_transaction",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 24, 20, 6, 8, 45551)
            ),
        ),
    ]
