# Generated by Django 4.1.7 on 2023-04-26 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_alter_deal_time_deal_historicaldeal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deal",
            old_name="quantity",
            new_name="in_quantity",
        ),
        migrations.RenameField(
            model_name="deal",
            old_name="lot_price",
            new_name="lot_exchange_rate",
        ),
        migrations.RenameField(
            model_name="deal",
            old_name="paid",
            new_name="out_quantity",
        ),
        migrations.RenameField(
            model_name="historicaldeal",
            old_name="asset",
            new_name="in_asset",
        ),
        migrations.RenameField(
            model_name="historicaldeal",
            old_name="quantity",
            new_name="in_quantity",
        ),
        migrations.RenameField(
            model_name="historicaldeal",
            old_name="lot_price",
            new_name="lot_exchange_rate",
        ),
        migrations.RenameField(
            model_name="historicaldeal",
            old_name="paid",
            new_name="out_quantity",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="payment_currency",
        ),
        migrations.RemoveField(
            model_name="historicaldeal",
            name="payment_currency",
        ),
        migrations.AddField(
            model_name="deal",
            name="in_asset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="in_asset",
                to="portfolio.asset",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deal",
            name="note",
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deal",
            name="out_asset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="out_asset",
                to="portfolio.asset",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldeal",
            name="note",
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldeal",
            name="out_asset",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portfolio.asset",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="time_deal",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 53, 32, 339691)
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeal",
            name="time_deal",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 53, 32, 339691)
            ),
        ),
    ]
