# Generated by Django 4.1.7 on 2023-04-26 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0024_rename_quantity_deal_in_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="note",
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="time_deal",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 59, 46, 769292)
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeal",
            name="note",
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldeal",
            name="time_deal",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 59, 46, 769292)
            ),
        ),
    ]
