# Generated by Django 4.1.7 on 2023-04-27 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0026_alter_deal_time_deal_alter_historicaldeal_time_deal_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="settlement_currency",
        ),
        migrations.AddField(
            model_name="asset",
            name="currency_influence",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="portfolio.asset",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="asset",
            name="country",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="asset",
            name="isin",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="issuer",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="asset",
            name="ticker",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="deal",
            name="exchange",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="deal",
            name="time_deal",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="historicaldeal",
            name="exchange",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="historicaldeal",
            name="time_deal",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=50)),
                ("broker", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.portfolio",
                    ),
                ),
            ],
        ),
    ]
