# Generated by Django 4.1.7 on 2023-04-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0029_rename_account_name_account_name_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="portfolio.account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldeal",
            name="account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portfolio.account",
            ),
        ),
    ]
