# Generated by Django 4.1.7 on 2023-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0032_alter_deal_exchange_alter_historicaldeal_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type_transaction",
            field=models.IntegerField(
                choices=[
                    (1, "Fund"),
                    (2, "Profit"),
                    (3, "Fee"),
                    (4, "Tax"),
                    (5, "Withdrawal"),
                ],
                default=2,
            ),
        ),
    ]
