# Generated by Django 4.1.7 on 2023-05-04 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfolio", "0034_transaction_changed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="icons/"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.deal",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.position",
            ),
        ),
    ]
