# Generated by Django 4.1.7 on 2023-05-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0035_alter_asset_icon_alter_transaction_changed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="changed_by",
        ),
    ]
